name: rs

env:
  REGISTRY: ghcr.io
  CONTEXT: rs
  IMAGE_NAME: ${{ github.repository }}/rs

on:
  push:
    # Only trigger on tags that start with 'rs-'
    tags:        
      - 'rs-*'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: ${{ env.CONTEXT }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            REGISTRY=${{ env.REGISTRY }}
            REPO=ousso11/docker-images
            BASE_TAG=latest

      - name: Make the image public using GitHub API
        run: |
          curl -X PATCH \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/orgs/${{ github.repository_owner }}/packages/container/${{ github.repository }}/rs/visibility \
          -d '{"visibility":"public"}'
