name: rs

env:
  REGISTRY: ghcr.io
  CONTEXT: rs
  IMAGE_NAME: ${{ github.repository }}/rs

on:
  push:
    # Only trigger on tags that start with 'rs-'
    tags:        
      - 'rs-*'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest-4-cores
    permissions:
      contents: read
      packages: write
      attestations: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # === CRITICAL: Free up disk space first ===
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Additional cleanup and disk space check
        run: |
          sudo rm -rf /usr/local/share/boost || true
          sudo rm -rf /opt/ghc || true
          sudo rm -rf /usr/share/dotnet || true
          docker system prune -af || true
          echo "Available disk space after cleanup:"
          df -h /
        
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=main
            type=raw,value={{tag}},enable={{is_default_branch}}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.CONTEXT }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64  # Single platform to save space
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            REGISTRY=${{ env.REGISTRY }}
            REPO=ousso11/docker-images
            BASE_TAG=latest
            BUILDKIT_INLINE_CACHE=1

      - name: Make the image public using GitHub API
        run: |
          curl -X PATCH \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/orgs/${{ github.repository_owner }}/packages/container/${{ github.repository }}/rs/visibility \
          -d '{"visibility":"public"}'
